/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoCoursesRouteImport } from './routes/video-courses'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as TalksRouteImport } from './routes/talks'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthStatusRouteImport } from './routes/auth-status'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoCoursesSlugRouteImport } from './routes/video-courses.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminVideoCoursesRouteImport } from './routes/_authenticated/admin.video-courses'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin.theme'
import { Route as AuthenticatedAdminTalksEventsRouteImport } from './routes/_authenticated/admin.talks-events'
import { Route as AuthenticatedAdminTalksRouteImport } from './routes/_authenticated/admin.talks'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin.skills'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminQuickStatsRouteImport } from './routes/_authenticated/admin.quick-stats'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminNavigationRouteImport } from './routes/_authenticated/admin.navigation'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminInternationalExperienceRouteImport } from './routes/_authenticated/admin.international-experience'
import { Route as AuthenticatedAdminHomeRouteImport } from './routes/_authenticated/admin.home'
import { Route as AuthenticatedAdminErrorLogsRouteImport } from './routes/_authenticated/admin.error-logs'
import { Route as AuthenticatedAdminEducationRouteImport } from './routes/_authenticated/admin.education'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminCertificationsRouteImport } from './routes/_authenticated/admin.certifications'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'

const VideoCoursesRoute = VideoCoursesRouteImport.update({
  id: '/video-courses',
  path: '/video-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksRoute = TalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatusRoute = AuthStatusRouteImport.update({
  id: '/auth-status',
  path: '/auth-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCoursesSlugRoute = VideoCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideoCoursesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVideoCoursesRoute =
  AuthenticatedAdminVideoCoursesRouteImport.update({
    id: '/video-courses',
    path: '/video-courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTalksEventsRoute =
  AuthenticatedAdminTalksEventsRouteImport.update({
    id: '/talks-events',
    path: '/talks-events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTalksRoute = AuthenticatedAdminTalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuickStatsRoute =
  AuthenticatedAdminQuickStatsRouteImport.update({
    id: '/quick-stats',
    path: '/quick-stats',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNavigationRoute =
  AuthenticatedAdminNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInternationalExperienceRoute =
  AuthenticatedAdminInternationalExperienceRouteImport.update({
    id: '/international-experience',
    path: '/international-experience',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomeRoute = AuthenticatedAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminErrorLogsRoute =
  AuthenticatedAdminErrorLogsRouteImport.update({
    id: '/error-logs',
    path: '/error-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEducationRoute =
  AuthenticatedAdminEducationRouteImport.update({
    id: '/education',
    path: '/education',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificationsRoute =
  AuthenticatedAdminCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-status': typeof AuthStatusRoute
  '/blog': typeof BlogRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/talks': typeof TalksRoute
  '/transform': typeof TransformRoute
  '/video-courses': typeof VideoCoursesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/video-courses/$slug': typeof VideoCoursesSlugRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/certifications': typeof AuthenticatedAdminCertificationsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/education': typeof AuthenticatedAdminEducationRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/international-experience': typeof AuthenticatedAdminInternationalExperienceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quick-stats': typeof AuthenticatedAdminQuickStatsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/talks': typeof AuthenticatedAdminTalksRoute
  '/admin/talks-events': typeof AuthenticatedAdminTalksEventsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/video-courses': typeof AuthenticatedAdminVideoCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-status': typeof AuthStatusRoute
  '/blog': typeof BlogRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/talks': typeof TalksRoute
  '/transform': typeof TransformRoute
  '/video-courses': typeof VideoCoursesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/video-courses/$slug': typeof VideoCoursesSlugRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/certifications': typeof AuthenticatedAdminCertificationsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/education': typeof AuthenticatedAdminEducationRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/international-experience': typeof AuthenticatedAdminInternationalExperienceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quick-stats': typeof AuthenticatedAdminQuickStatsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/talks': typeof AuthenticatedAdminTalksRoute
  '/admin/talks-events': typeof AuthenticatedAdminTalksEventsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/video-courses': typeof AuthenticatedAdminVideoCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-status': typeof AuthStatusRoute
  '/blog': typeof BlogRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/talks': typeof TalksRoute
  '/transform': typeof TransformRoute
  '/video-courses': typeof VideoCoursesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/video-courses/$slug': typeof VideoCoursesSlugRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/certifications': typeof AuthenticatedAdminCertificationsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/education': typeof AuthenticatedAdminEducationRoute
  '/_authenticated/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/_authenticated/admin/home': typeof AuthenticatedAdminHomeRoute
  '/_authenticated/admin/international-experience': typeof AuthenticatedAdminInternationalExperienceRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/quick-stats': typeof AuthenticatedAdminQuickStatsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/talks': typeof AuthenticatedAdminTalksRoute
  '/_authenticated/admin/talks-events': typeof AuthenticatedAdminTalksEventsRoute
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/admin/video-courses': typeof AuthenticatedAdminVideoCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-status'
    | '/blog'
    | '/collaborate'
    | '/companies'
    | '/contact'
    | '/courses'
    | '/impact'
    | '/learn'
    | '/privacy'
    | '/projects'
    | '/talks'
    | '/transform'
    | '/video-courses'
    | '/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/video-courses/$slug'
    | '/admin/about'
    | '/admin/blog'
    | '/admin/certifications'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/education'
    | '/admin/error-logs'
    | '/admin/home'
    | '/admin/international-experience'
    | '/admin/messages'
    | '/admin/navigation'
    | '/admin/partners'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/quick-stats'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/talks'
    | '/admin/talks-events'
    | '/admin/theme'
    | '/admin/video-courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-status'
    | '/blog'
    | '/collaborate'
    | '/companies'
    | '/contact'
    | '/courses'
    | '/impact'
    | '/learn'
    | '/privacy'
    | '/projects'
    | '/talks'
    | '/transform'
    | '/video-courses'
    | '/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/video-courses/$slug'
    | '/admin/about'
    | '/admin/blog'
    | '/admin/certifications'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/education'
    | '/admin/error-logs'
    | '/admin/home'
    | '/admin/international-experience'
    | '/admin/messages'
    | '/admin/navigation'
    | '/admin/partners'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/quick-stats'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/talks'
    | '/admin/talks-events'
    | '/admin/theme'
    | '/admin/video-courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/auth-status'
    | '/blog'
    | '/collaborate'
    | '/companies'
    | '/contact'
    | '/courses'
    | '/impact'
    | '/learn'
    | '/privacy'
    | '/projects'
    | '/talks'
    | '/transform'
    | '/video-courses'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/video-courses/$slug'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/certifications'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/education'
    | '/_authenticated/admin/error-logs'
    | '/_authenticated/admin/home'
    | '/_authenticated/admin/international-experience'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/navigation'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/quick-stats'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/talks'
    | '/_authenticated/admin/talks-events'
    | '/_authenticated/admin/theme'
    | '/_authenticated/admin/video-courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthStatusRoute: typeof AuthStatusRoute
  BlogRoute: typeof BlogRouteWithChildren
  CollaborateRoute: typeof CollaborateRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  LearnRoute: typeof LearnRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TalksRoute: typeof TalksRoute
  TransformRoute: typeof TransformRoute
  VideoCoursesRoute: typeof VideoCoursesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-courses': {
      id: '/video-courses'
      path: '/video-courses'
      fullPath: '/video-courses'
      preLoaderRoute: typeof VideoCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks': {
      id: '/talks'
      path: '/talks'
      fullPath: '/talks'
      preLoaderRoute: typeof TalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-status': {
      id: '/auth-status'
      path: '/auth-status'
      fullPath: '/auth-status'
      preLoaderRoute: typeof AuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-courses/$slug': {
      id: '/video-courses/$slug'
      path: '/$slug'
      fullPath: '/video-courses/$slug'
      preLoaderRoute: typeof VideoCoursesSlugRouteImport
      parentRoute: typeof VideoCoursesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/video-courses': {
      id: '/_authenticated/admin/video-courses'
      path: '/video-courses'
      fullPath: '/admin/video-courses'
      preLoaderRoute: typeof AuthenticatedAdminVideoCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/talks-events': {
      id: '/_authenticated/admin/talks-events'
      path: '/talks-events'
      fullPath: '/admin/talks-events'
      preLoaderRoute: typeof AuthenticatedAdminTalksEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/talks': {
      id: '/_authenticated/admin/talks'
      path: '/talks'
      fullPath: '/admin/talks'
      preLoaderRoute: typeof AuthenticatedAdminTalksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quick-stats': {
      id: '/_authenticated/admin/quick-stats'
      path: '/quick-stats'
      fullPath: '/admin/quick-stats'
      preLoaderRoute: typeof AuthenticatedAdminQuickStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/navigation': {
      id: '/_authenticated/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AuthenticatedAdminNavigationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/international-experience': {
      id: '/_authenticated/admin/international-experience'
      path: '/international-experience'
      fullPath: '/admin/international-experience'
      preLoaderRoute: typeof AuthenticatedAdminInternationalExperienceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/home': {
      id: '/_authenticated/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AuthenticatedAdminHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/error-logs': {
      id: '/_authenticated/admin/error-logs'
      path: '/error-logs'
      fullPath: '/admin/error-logs'
      preLoaderRoute: typeof AuthenticatedAdminErrorLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/education': {
      id: '/_authenticated/admin/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AuthenticatedAdminEducationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certifications': {
      id: '/_authenticated/admin/certifications'
      path: '/certifications'
      fullPath: '/admin/certifications'
      preLoaderRoute: typeof AuthenticatedAdminCertificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCertificationsRoute: typeof AuthenticatedAdminCertificationsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminEducationRoute: typeof AuthenticatedAdminEducationRoute
  AuthenticatedAdminErrorLogsRoute: typeof AuthenticatedAdminErrorLogsRoute
  AuthenticatedAdminHomeRoute: typeof AuthenticatedAdminHomeRoute
  AuthenticatedAdminInternationalExperienceRoute: typeof AuthenticatedAdminInternationalExperienceRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNavigationRoute: typeof AuthenticatedAdminNavigationRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminQuickStatsRoute: typeof AuthenticatedAdminQuickStatsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminTalksRoute: typeof AuthenticatedAdminTalksRoute
  AuthenticatedAdminTalksEventsRoute: typeof AuthenticatedAdminTalksEventsRoute
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedAdminVideoCoursesRoute: typeof AuthenticatedAdminVideoCoursesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCertificationsRoute: AuthenticatedAdminCertificationsRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminEducationRoute: AuthenticatedAdminEducationRoute,
  AuthenticatedAdminErrorLogsRoute: AuthenticatedAdminErrorLogsRoute,
  AuthenticatedAdminHomeRoute: AuthenticatedAdminHomeRoute,
  AuthenticatedAdminInternationalExperienceRoute:
    AuthenticatedAdminInternationalExperienceRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNavigationRoute: AuthenticatedAdminNavigationRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminQuickStatsRoute: AuthenticatedAdminQuickStatsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminTalksRoute: AuthenticatedAdminTalksRoute,
  AuthenticatedAdminTalksEventsRoute: AuthenticatedAdminTalksEventsRoute,
  AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
  AuthenticatedAdminVideoCoursesRoute: AuthenticatedAdminVideoCoursesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface VideoCoursesRouteChildren {
  VideoCoursesSlugRoute: typeof VideoCoursesSlugRoute
}

const VideoCoursesRouteChildren: VideoCoursesRouteChildren = {
  VideoCoursesSlugRoute: VideoCoursesSlugRoute,
}

const VideoCoursesRouteWithChildren = VideoCoursesRoute._addFileChildren(
  VideoCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthStatusRoute: AuthStatusRoute,
  BlogRoute: BlogRouteWithChildren,
  CollaborateRoute: CollaborateRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ImpactRoute: ImpactRoute,
  LearnRoute: LearnRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TalksRoute: TalksRoute,
  TransformRoute: TransformRoute,
  VideoCoursesRoute: VideoCoursesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
