// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function sanitizeEnvValue(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function createPlaceholderClient(message: string): SupabaseClient<Database> {
  return createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
    global: {
      fetch: () => Promise.reject(new Error(message)),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

function createSupabaseClient(): SupabaseClient<Database> {
  // Strictly read from Vite env vars so the build is portable to any host
  // (e.g. Vercel). Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY
  // (VITE_SUPABASE_ANON_KEY is accepted as an alias).
  const rawUrl =
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_URL) ||
    sanitizeEnvValue(typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const rawKey =
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_ANON_KEY) ||
    sanitizeEnvValue(
      typeof process !== 'undefined'
        ? process.env?.SUPABASE_PUBLISHABLE_KEY || process.env?.SUPABASE_ANON_KEY
        : undefined,
    );

  const SUPABASE_URL = rawUrl ? rawUrl.replace(/\/+$/, '') : undefined;
  const SUPABASE_PUBLISHABLE_KEY = rawKey;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    return createPlaceholderClient(message);
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (err) {
    const message = `Failed to initialize Supabase client: ${err instanceof Error ? err.message : String(err)}`;
    console.error(`[Supabase] ${message}`, err);
    return createPlaceholderClient(message);
  }
}

let _supabase: SupabaseClient<Database> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

